### ISSUE TITLE
Publish the built app to npm instead of github release

### ISSUE THREAD

**Issue by dinoboff** [singpath/classmentors#102]
When a new tag is pushed github, travis pushes the build app as a release artefact:
https://github.com/singpath/classmentors/releases

By releasing it to npm instead it would simplify the travis config and allow to include command to setup/update the firebase database and hosting.

**Comment by SingaporeClouds** [comment]
This is not needed at this time. We will focus on simplicity for cloning the gh-pages branch. We can focus on simplifying setup for developers after that. The current process appears to be working for the current developers.
