### ISSUE TITLE
Publish master to firebase hoisting instead of gh-pages

### ISSUE THREAD

**Issue by dinoboff** [singpath/classmentors#104]
Assuming it's easy to create an oauth token with limited roles to update database and hosting, it might ease contributors travis setup.

**Comment by SingaporeClouds** [comment]
So is the idea to publish to singpath-play.firebaseio.com hosting rather than gh-pages?

**Comment by dinoboff** [comment]
Yes, assuming it easier to setup with travis. Upstream can keep publishing to gh-pages. But for example, dinoboff/classmentors-1 would publish singpath-dinoboff.firebaseio.com.

Using travis cli, a contributor would enable travis for his fork, set an private travis variable for the firebase Oauth token and travis variable for the firebase app settings.

**Comment by dinoboff** [comment]
- `firebase login-ci` provide the firebase oauth.
- #103 should provide the firebase app settings in an easy form to upload on travis.

**Comment by SingaporeClouds** [comment]
The idea for gh-pages deployment was just to provide users with a quick way to get something to play with.  When you fork the Github repo, your gh-pages branch would be a live deployment of ClassMentors using the singpath-play firebase url. Then you could just edit the Firebase url to begin working with your own data. You would then just need to setup the Firebase security rules and login authorization in the Firebase GUI, but you wouldn't need to deploy anything.  

Deploying to gh-pages was not intended to let you do anything much more than change the firebase url to start working with your own data and database url. You would need more experience and instructions to install and use the npm and firebase commandline tools.
