### ISSUE TITLE
Can no longer create events after recent security rule changes. 

### ISSUE THREAD

**Issue by SingaporeClouds** [singpath/classmentors#110]
Can no longer create events as the admin after recent security rule changes. 

Please add a test that confirms that admins can always create events. 

![image](https://cloud.githubusercontent.com/assets/116418/18624813/f0f06c9c-7e7c-11e6-87ea-9234c8ea1acf.png)

**Comment by dinoboff** [comment]
@SingaporeClouds 

Could it be that admin user has not Premium role as well?

I will add rule to check for admin role too.

**Comment by SingaporeClouds** [comment]
I am configured as a premium user and admin user in Firebase and I still could not create a new event. So it is possible that neither the admin or the premium users rules are working properly.

**Comment by dinoboff** [comment]
I fixed the rules for admin. Once deployed, it should work. I will test it actually works.

**Comment by dinoboff** [comment]
It creating the event but failing to save it in the user profile as a created event. Checking what's the issue.
