### ISSUE TITLE
Let users other that the user to request a refresh of a profile

### ISSUE THREAD

**Issue by dinoboff** [singpath/classmentors#115]
Who should be allow to request an update?

Admin, premium users or any registered user?

**Comment by SingaporeClouds** [comment]
Any register user can add a task to the queue to update their profile and achievements.

Event owners can add tasks to the queue to update any participants in their events

Cohort owners can add tasks to update everyone in the cohort.

The admin can add tasks to update anyone's profile and achievements.

Chris

**Comment by dinoboff** [comment]
@SingaporeClouds Adding to the queue is ok (no rules yet).

The question is about the flag to disable the refresh button on the profile page for 1 minute and who can see that button. A timestamp is added to the user profile for each service and checked before showing the refresh button to the profile owner.

There's no rule to prevent anything (other than who can set the that timestamp), it's only used by the profile UI. The event/cohort view can create a task regardless of that timestamp.

Who can refresh the profile from the profile page?

Note that's easier to allow all user allowed to create cohort/event than to check if they have created a cohort/event the profile owner has joined.

**Comment by SingaporeClouds** [comment]
I believe this may be more complex than the requirement called for. All
that was requested was to hide the button for 60 seconds to prevent users
from clicking on the button multiple times while achievements were being
downloaded. I am unclear why any database changes were necessary.

If you have something more elegant that is fine, but all that was requested
was something in the GUI along the lines of:

var updateAchievements = function() {
    // .. existing code.
    var hidden = true;
 setTimeout(function(){ hidden=false; }, 60000);
}
