### ISSUE TITLE
Event progress loading error

### ISSUE THREAD

**Issue by shiquan-lim** [singpath/classmentors#122]
Method update progress in services.js fails due to highlighted line. (See below). I have removed it temporarily in order to facilitate continued use of the portal in class.

![image](https://cloud.githubusercontent.com/assets/19287054/18941863/359d9c94-8647-11e6-93f0-d0a1963ddccf.png)

**Comment by dinoboff** [comment]
Are you sure it was failing? It should just have shown a deprecated warning console message.

Nonetheless it's shouldn't fetch the badges anymore but the user achievement (TODO).

**Comment by dinoboff** [comment]
@shiquan-lim

**Comment by dinoboff** [comment]
@shiquan-lim the problem is with Code School. It wasn't defined in the list of services.

Also, you shouldn't comment them out be replace each with an empty array.
