### ISSUE TITLE
Failure to join events

### ISSUE THREAD

**Issue by shiquan-lim** [singpath/classmentors#141]
See error below

![image](https://cloud.githubusercontent.com/assets/19287054/19436140/112dc4ac-94a1-11e6-9925-4f083f8e87ef.png)

**Comment by SingaporeClouds** [comment]
The error message that I get when trying to join events is more like this one. 
![image](https://cloud.githubusercontent.com/assets/116418/19441411/3c05668c-94b8-11e6-8f7b-953728314a34.png)

**Comment by dinoboff** [comment]
I am checking it now. Are both errors occurring with the current master?

**Comment by SingaporeClouds** [comment]
Yes

**Comment by dinoboff** [comment]
@shiquan-lim I cannot reproduce this error. Which browser?

**Comment by dinoboff** [comment]
@shiquan-lim if still have the issue, please reopen this issue
