### ISSUE TITLE
Event rankings are continually polling and getting errors for some reason

### ISSUE THREAD

**Issue by SingaporeClouds** [singpath/classmentors#143]
![image](https://cloud.githubusercontent.com/assets/116418/19440637/3900123c-94b5-11e6-8144-a209609601f4.png)

**Comment by SingaporeClouds** [comment]
Seems to only happen for more recent events. When I open older events, I don't see this issue. This is a critical bug since the errors keep piling up on every system that might be viewing the ranking.

**Comment by dinoboff** [comment]
Have you deployed the rules with the new build?

**Comment by dinoboff** [comment]
@SingaporeClouds can check that event again after? I have deploy the rules in case they were not deployed.

Also that it affect the event owner? Event Assistants? both?

**Comment by SingaporeClouds** [comment]
The security rules get deployed with the code. Both issues were seen after a deploy.

I saw both issues as the admin  and event owner. A non-owner also saw the issues.

The security rules can be relaxed for now until these issues are resolved. Being able to join events and no errors in the ranking console should be the initial priorities.

**Comment by SingaporeClouds** [comment]
I just confirmed that this issue does not occur for users who are not in the event and are not the event owner. The event owner is trying to do something to eventParticipants repeatedly. 

FIREBASE WARNING: update at /classMentors/eventParticipants/-KO3mr-Oe3qcRfpHUo8I/peguin40 failed: permission_denied

**Comment by dinoboff** [comment]
If it's for recent event, it could be related to the participants data `joinedAt` property.

**Comment by dinoboff** [comment]
I couldn't investigate that event. I loosen the rule about the joinedAT property. Can you check if it solved it?

**Comment by SingaporeClouds** [comment]
I still see the same issue. It may be because I'm admin. What would the admin or event owner be trying to update from the ranking page? Now that all achievements are being checked server-side, the event owner shouldn't be trying to write anything. The event owner and admin should just be reading. For some reason, my browser is trying to update all of the:

FIREBASE WARNING: update at /classMentors/eventParticipants/-KO3mr-Oe3qcRfpHUo8I/<publicId> failed: permission_denied

**Comment by SingaporeClouds** [comment]
I can duplicate this issue on singpath-play for the following event. /#/events/-KJiQi8IBdEK6azah_uj

The problem appears to be with monitorEvent in services.js. The event owner or admin may be the only one trying to run this service. If I change the delay from 300 to 300000, I can make the issue go away. The monitor function will run every 300 seconds rather than 300ms. However, I will still get the same permission_denied errors when the monitor event eventually runs.  

```
      monitorEvent: function(event, tasks, participants, solutions, progress) {
        var tid;
        var delay = 300000;
```

**Comment by dinoboff** [comment]
@SingaporeClouds I got some sample data and can debug the permission issue...

**Comment by dinoboff** [comment]
I am sending a PR.

**Comment by dinoboff** [comment]
#150 fixes it.

I deployed the change and the PR just need to include a regression test

**Comment by dinoboff** [comment]
The PR is ready to be merged.
