### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by dinoboff** [singpath/classmentors#144]
`npm run build` fails with last PR.

**Comment by SingaporeClouds** [comment]
I think it started failing after an npm install rather than after the last PR.

**Comment by dinoboff** [comment]
I am refering to https://travis-ci.org/singpath/classmentors/builds/168211135

**Comment by SingaporeClouds** [comment]
That is the same error that I am seeing locally as well on a fresh npm install.

**Comment by dinoboff** [comment]
The PR gives details on why the previous PR changes to packages.json broke the build.
