### ISSUE TITLE
Fix/remove code combat

### ISSUE THREAD

**Issue by dinoboff** [singpath/classmentors#16]
The profile does not show code combat achievements.

Should it be removed? 
Is there something to fix?

**Comment by SingaporeClouds** [comment]
Code Combat had made the badge url private. They just made it public again
for me. I will update the firebase-queue worker to check for CodeCombat
achievements and add Code Combat back.

On Mon, Jun 20, 2016 at 12:55 AM, Damien Lebrun notifications@github.com
wrote:

> The profile does not show code combat achievements.
> 
> Should it be removed?
> Is there something to fix?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/singpath/classmentors/issues/16, or mute the thread
> https://github.com/notifications/unsubscribe/AAHGwp7VmXMI3cpzxIs4R-FyXxjy4Myaks5qNXR6gaJpZM4I5NDm
> .

## 

Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
