### ISSUE TITLE
creating ID

### ISSUE THREAD

**Issue by SandraBoesch** [singpath/classmentors#42]
The user has to pick an ID but that is rather confusing. It looks as if you are supposed to know what your id is. Rather than create an id. Paybe clarify that section to please create your ID. 
![screen shot 2016-07-28 at 4 16 45 pm](https://cloud.githubusercontent.com/assets/1318387/17285338/bbbe4cc8-57f4-11e6-9f22-42bc86207d67.png)

**Comment by SingaporeClouds** [comment]
New profile screen provides additional information and no longer requires country or school to be selected by default.
