### ISSUE TITLE
Pop up ok button does not work

### ISSUE THREAD

**Issue by SandraBoesch** [singpath/classmentors#43]
at this window when you click the ok button the button does not work - user has to press enter on keyboard to enter the password.
![screen shot 2016-07-28 at 4 18 59 pm](https://cloud.githubusercontent.com/assets/1318387/17285387/f3d47448-57f4-11e6-9551-1cabb0a462eb.png)

**Comment by ManasBhalla** [comment]
I encountered the same issue. 
The login works with enter but does not work by clicking "ok" button.
