### ISSUE TITLE
Hide the refresh achievements button on profile page for 1 minute after pressing it.

### ISSUE THREAD

**Issue by SingaporeClouds** [singpath/classmentors#74]
Provide more feedback to users that updates are occurring by hiding the refresh button and changing the last updated time to "updating". Then unhide the button after a 60 second timer expires. 
Show the last updated time and the button once the 60 second timer expires.

**Comment by dinoboff** [comment]
I will set it to 0 or -1 when updating. We should add a field to save the last update request. The backend could use it to rate limit updates
