### ISSUE TITLE
Create an admin route and partial to support 3rd party service configuration. 

### ISSUE THREAD

**Issue by SingaporeClouds** [singpath/classmentors#76]
Create an /admin partial that an admin can navigate to but only the admin will be able to access. 
There does not need to be a link or other GUI way to reach this route. 
This partial will be where the classmentors admin can configure items such as which services to show on users'  profiles. 
Initially, admin will be able to configure whether FreeCodeCamp, CodeCombat, and CodeSchool are displayed. There can be a simple toggle for each. Only the GUI for these services needs to be hidden from profiles when these switches are toggled. 
The admin page will also have a way for users to configure additional CodeVantage-based services by providing a link to the CodeVantage-based public achievements, the name of the service, and a link to the GUI for the service. 
This should allow new ClassMentors instances to be extensible to extensible to support any number of CodeVantage-based services. 
- [x] add firebase rules.
- [x] add admin form.
- [x] add service settings to switch whether FreeCodeCamp, CodeCombat, and CodeSchool are displayed

**Comment by dinoboff** [comment]
#85 adds the security rules and admin form.
- The rules expect settings to be defined at classMentors/settings/$settingId. 
- a setting must have 'title', 'value' and 'type' attributes. Type can be anything but if it's set to "boolean" it will be shown as a switch in the admin form.

**Comment by dinoboff** [comment]
@SingaporeClouds To deploy the changes (once the last PR is merged), you need need to set the default settings:

``` bash
npm install -g firebase-tools@3
npm install
npm run build
/bin/classmentors.js -P firebase-singpath setup
firebase -P firebase-singpath deploy
```

**Comment by dinoboff** [comment]
@SingaporeClouds Note that the admin page is currently visible to anybody but the form is disable for non admin. it mirrors the rules for the settings.
