### ISSUE TITLE
Include server timestamp to eventParticipants records when users join events. 

### ISSUE THREAD

**Issue by SingaporeClouds** [singpath/classmentors#78]
This should make it easier to extract a timeline for when users joined events. Event join times can then be aggregated to show total cohort participants over time.  
classMentors/eventParticipants/<eventId>/<publicID>/joined = serverTimstamp

**Comment by dinoboff** [comment]
@SingaporeClouds How should we handle existing records?

**Comment by SingaporeClouds** [comment]
We can leave existing records blank and have the logic check if there is a joined property or not. Then it should work for all future joins.

**Comment by dinoboff** [comment]
@SingaporeClouds The PR adds a timestamp named "joinedAt" for consistency with other timestamp name.

Is it ok?

**Comment by SingaporeClouds** [comment]
Yes. If we have used the property name joinedAt previously, we can continue
using that property name. It seems descriptive enough.
