### ISSUE TITLE
Object.assign(service.mixin) issue reported with screenshot. See using a Mac. 

### ISSUE THREAD

**Issue by SingaporeClouds** [singpath/classmentors#87]
![image](https://cloud.githubusercontent.com/assets/116418/18259782/75babfe4-741a-11e6-9c26-718ce60155f0.png)

**Comment by dinoboff** [comment]
@SingaporeClouds which browser?

**Comment by SingaporeClouds** [comment]
Unknown at this time. My guess would be Safari on a Mac based on the
Facebook post.
