### ISSUE TITLE
App page loading failing

### ISSUE THREAD

**Issue by shiquan-lim** [singpath/classmentors#98]
Unable to navigate to cohorts, events, and profile unless it is a fresh login. Nav bar buttons are clickable, and no error in console. But the partial for each respective function appears blank. Only logging out and in resolves this issue.

![image](https://cloud.githubusercontent.com/assets/19287054/18534844/b08115fc-7b21-11e6-9419-d4d0bb15b7d3.png)

**Comment by dinoboff** [comment]
master seems to work http://singpath.github.io/classmentors/

**Comment by dinoboff** [comment]
Maybe the built app is not affected

**Comment by dinoboff** [comment]
I think it's related to auth. spfAuth.$loaded() must be hanging.
